---
timesync_ntp_servers:
  - hostname: 0.pl.pool.ntp.org
    iburst: yes
  - hostname: 1.pl.pool.ntp.org
    iburst: yes
  - hostname: 2.pl.pool.ntp.org
    iburst: yes
  - hostname: 3.pl.pool.ntp.org
    iburst: yes
timezone_var: 'Europe/Warsaw'
...
