---
- name: Variables
  hosts: control
  #gather_facts: false
  tasks:
    - debug:
        msg: "{{ ansible_facts['ansible_mounts'] }}"

    - debug:
        msg: "{{ group_names }}"

    - debug:
        msg: "{{ groups }}"

    - debug:
        msg: "{{ inventory_hostname }}"

    - debug:
        msg: "{{ inventory_hostname_short }}"

    - debug:
        #msg: "{{ hostvars }}"
        #msg: "{{ hostvars['control']['ansible_facts'] }}"
        msg: "{{ hostvars['control']['ansible_local'] }}"

    - debug:
        msg: "{{ inventory_hostname_short + '/path/' + '.extension' }}"

...
