---
- name: Check services facts
  hosts: control
  tasks:
    - name: gather service facts
      service_facts:

    - name: print services facts
      debug:
        var: ansible_facts['services']

    - name: print services facts
      debug:
        var: ansible_facts['services']['NetworkManager.service']
...
