---
mac0: "08:00:27:ec:6d:66"
mac1: "08:00:27:71:46:e2"
mac2: "08:00:27:e5:9a:12"
mac3: "08:00:27:3a:6b:77"


network_connections:
  - name: lab_conn
    state: up
    type: ethernet
    mac: "{{ mac2 }}"
    ip:
      dhcp4: no
      address:
        - "192.168.22.33/24"
...
