syntax on
filetype plugin indent on
autocmd Filetype yml setlocal ai sw=2 ts=2 sts=2 et cuc cul
set number
colorscheme peachpuff
highlight CursorColumn ctermbg=DarkBlue
"highlight CursorColumn ctermbg=1
"highlight CursorColumn ctermbg=236

let g:markdown_folding = 1
au FileType markdown setlocal foldlevel=1
