syntax on
filetype plugin indent on
autocmd Filetype yaml setlocal ai sw=5 ts=5 sts=5 et cuc cul
set number
" colorscheme peachpuff
colorscheme slate
highlight CursorColumn ctermbg=DarkBlue
" highlight CursorColumn ctermbg=1
" highlight CursorColumn ctermbg=236

let g:markdown_folding = 1
au FileType markdown setlocal foldlevel=1
