syntax on
filetype plugin indent on
autocmd Filetype yaml setlocal ai sw=2 ts=2 sts=2 et cuc cul
set number
highlight CursorColumn ctermbg=DarkBlue
"highlight CursorColumn ctermbg=1
"highlight CursorColumn ctermbg=236
