---
# tasks file for sample-apache
- name: install pkgs
  dnf:
    name: "{{ pkg_list }}"
    state: present

- name: set firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - '80/tcp'
    - '443/tcp'

- name: copy index.html template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: create {{ systemd_unit_name }}.service
  copy:
    src: "{{ systemd_unit_name + '.service'}}"
    dest: "{{ systemd_unit_installation_path + systemd_unit_name + '.service' }}"
  notify: reload-systemd

- name: create {{ systemd_unit_name }}.path
  template:
    src: "{{ systemd_unit_name + '.path.j2'}}"
    dest: "{{ systemd_unit_installation_path + systemd_unit_name + '.path' }}"
  notify: reload-systemd
- meta: flush_handlers

- name: enable {{ systemd_unit_name }}.path
  service:
    name: "{{ systemd_unit_name + '.service' }}"
    # stopped on purpose, this unit should be started via WantedBy in path unit
    state: stopped
    enabled: true

- name: start apache
  service:
    name: httpd
    state: started
    enabled: true
...
