---
# tasks file for sample-apache
- name: install pkgs
  dnf:
    name: "{{ pkg_list }}"
    state: present

- name: start apache
  service:
    name: httpd
    state: started
    enabled: true

- name: set firewall
  firewalld:
    port: '80/tcp'
    permanent: true
    immediate: true
    state: enabled

- name: set firewall
  firewalld:
    port: '443/tcp'
    permanent: true
    immediate: true
    state: enabled

- name: copy template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    force: true
  notify: restart apache
...
