---
- name: Task 15 - Work with Ansible Facts
  hosts: database
  become: true
  vars:
    facts_path: /etc/ansible/facts.d
  tasks:
    - file:
        dest: "{{ facts_path }}"
        state: directory
    - copy:
        content: |
          [sample_exam]
          server_role=mysql
        dest: "{{ facts_path }}/custom.fact"
...
