---
- name: Task 3 - File Content
  hosts: all
  become: true
  tasks:
    - name: copy motd template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0444'
...
