---
- name: Task 3 - File Content proxy
  hosts: proxy
  become: true
  tasks:
    - name: Change motd file content
      copy:
        content: "Welcome to HAProxy server of group {{ group_names | to_nice_yaml }}\n"
        dest: /etc/motd

- name: Task 3 - File Content webservers
  hosts: webservers
  become: true
  tasks:
    - name: Change motd file content
      copy:
        content: "Welcome to apache server\n"
        dest: /etc/motd

- name: Task 3 - File Content database
  hosts: database
  become: true
  tasks:
    - name: Change motd file content
      copy:
        content: "Welcome to mySQL server\n"
        dest: /etc/motd
...
