---
- name: Task 13 - Use Conditionals to Control Play Execution
  hosts: all
  become: true
  tasks:

    - name: set swappiness when mem is more than 800MB
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: "ansible_facts['memory_mb']['real']['total'] >= 800"
      #when: "ansible_memory_mb.real.total >= 2048"
    
    - name: print message when mem is less than 800MB
      fail:
        msg: 'Server memory less than 2048MB'
      when: "ansible_facts['memory_mb']['real']['total'] <= 800"
      #when: "ansible_memory_mb.real.total <= 2048"
...
