---
pkg_list:
  - httpd
  - mod_ssl
  - php

# Configuration of systemd Unit for restarting httpd when file change
systemd_unit_name: restart-httpd
systemd_path_to_monitor: /var/www/html/index.html
systemd_unit_installation_path: /usr/lib/systemd/system/
...
